<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>28ec33d6-7923-41d6-85a2-1fa3b0096ba7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AptekaRu.DAL\AptekaRu.DAL.csproj" />
  </ItemGroup>

</Project>
