-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

BEGIN;

CREATE SCHEMA aptekaru;

CREATE TABLE IF NOT EXISTS aptekaru.clients
(
    id_client uuid NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    birthday date NOT NULL,
    sex boolean NOT NULL,
    email character varying(45) COLLATE pg_catalog."default",
    number_phone character varying(30) COLLATE pg_catalog."default" NOT NULL,
    confirmed_phone boolean NOT NULL,
    CONSTRAINT clients_pkey PRIMARY KEY (id_client)
);

CREATE TABLE IF NOT EXISTS aptekaru.drugs
(
    id_drag uuid NOT NULL,
    article integer NOT NULL,
    name character varying(60) COLLATE pg_catalog."default" NOT NULL,
    frontend_name character varying(60) COLLATE pg_catalog."default" NOT NULL,
    id_type_drag integer NOT NULL,
    manufacturer character varying(30) COLLATE pg_catalog."default",
    brand character varying(30) COLLATE pg_catalog."default",
    active_ingrediet character varying(54) COLLATE pg_catalog."default" NOT NULL,
    instruction text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT drugs_pkey PRIMARY KEY (id_drag)
);

CREATE TABLE IF NOT EXISTS aptekaru.employees
(
    id_employee uuid NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sex boolean NOT NULL,
    email character varying(45) COLLATE pg_catalog."default",
    number_phone character varying(30) COLLATE pg_catalog."default" NOT NULL,
    id_job_title integer,
    works_with date,
    CONSTRAINT employees_pkey PRIMARY KEY (id_employee)
);

CREATE TABLE IF NOT EXISTS aptekaru.images
(
    id_images uuid NOT NULL,
    id_drag uuid NOT NULL,
    path_img character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT images_pkey PRIMARY KEY (id_images)
);

CREATE TABLE IF NOT EXISTS aptekaru.items_purchases
(
    id_items_purchases uuid NOT NULL,
    id_purchase uuid NOT NULL,
    id_drag uuid NOT NULL,
    count integer NOT NULL,
    CONSTRAINT items_purchases_pkey PRIMARY KEY (id_items_purchases)
);

CREATE TABLE IF NOT EXISTS aptekaru.job_titles
(
    id_job_titles integer NOT NULL,
    name character varying(60) COLLATE pg_catalog."default" NOT NULL,
    wages numeric(15, 2) NOT NULL,
    CONSTRAINT job_titles_pkey PRIMARY KEY (id_job_titles)
);

CREATE TABLE IF NOT EXISTS aptekaru.pharmacies
(
    id_pharmacy uuid NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    address character varying(90) COLLATE pg_catalog."default" NOT NULL,
    operating_mode character varying(60) COLLATE pg_catalog."default" NOT NULL,
    phones character varying(90) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pharmacies_pkey PRIMARY KEY (id_pharmacy)
);

CREATE TABLE IF NOT EXISTS aptekaru.purchases
(
    id_purchase uuid NOT NULL,
    id_employee uuid NOT NULL,
    id_client uuid NOT NULL,
    date_purchase time with time zone NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    payment_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT purchases_pkey PRIMARY KEY (id_purchase)
);

CREATE TABLE IF NOT EXISTS aptekaru.shedules
(
    id_shedule uuid NOT NULL,
    id_employee uuid NOT NULL,
    id_work_shedule integer NOT NULL,
    id_pharmacie uuid NOT NULL,
    start time with time zone NOT NULL,
    "end" time with time zone NOT NULL,
    missed_hours integer NOT NULL,
    status boolean NOT NULL,
    CONSTRAINT shedules_pkey PRIMARY KEY (id_shedule)
);

CREATE TABLE IF NOT EXISTS aptekaru.supplies
(
    id_supplies uuid NOT NULL,
    id_pharmacy uuid NOT NULL,
    id_drug uuid NOT NULL,
    supplier character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    current_quantity integer NOT NULL,
    price numeric(15, 2) NOT NULL,
    date_production date NOT NULL,
    date_expiration date NOT NULL,
    date_delivery date NOT NULL,
    CONSTRAINT supplies_pkey PRIMARY KEY (id_supplies)
);

CREATE TABLE IF NOT EXISTS aptekaru.type_drags
(
    id_type_drag integer NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT type_drags_pkey PRIMARY KEY (id_type_drag)
);

CREATE TABLE IF NOT EXISTS aptekaru.work_shedules
(
    id_work_shedule integer NOT NULL,
    work_shedule character varying(3) COLLATE pg_catalog."default" NOT NULL,
    working_hours integer NOT NULL,
    CONSTRAINT work_shedules_pkey PRIMARY KEY (id_work_shedule)
);

ALTER TABLE IF EXISTS aptekaru.drugs
    ADD CONSTRAINT drugs_id_type_drag_fkey FOREIGN KEY (id_type_drag)
    REFERENCES aptekaru.type_drags (id_type_drag) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.employees
    ADD CONSTRAINT employees_id_job_title_fkey FOREIGN KEY (id_job_title)
    REFERENCES aptekaru.job_titles (id_job_titles) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.images
    ADD CONSTRAINT images_id_drag_fkey FOREIGN KEY (id_drag)
    REFERENCES aptekaru.drugs (id_drag) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.items_purchases
    ADD CONSTRAINT items_purchases_id_drag_fkey FOREIGN KEY (id_drag)
    REFERENCES aptekaru.drugs (id_drag) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.items_purchases
    ADD CONSTRAINT items_purchases_id_purchase_fkey FOREIGN KEY (id_purchase)
    REFERENCES aptekaru.purchases (id_purchase) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.purchases
    ADD CONSTRAINT purchases_id_client_fkey FOREIGN KEY (id_client)
    REFERENCES aptekaru.clients (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.purchases
    ADD CONSTRAINT purchases_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES aptekaru.employees (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.shedules
    ADD CONSTRAINT shedules_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES aptekaru.employees (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.shedules
    ADD CONSTRAINT shedules_id_pharmacie_fkey FOREIGN KEY (id_pharmacie)
    REFERENCES aptekaru.pharmacies (id_pharmacy) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.shedules
    ADD CONSTRAINT shedules_id_work_shedule_fkey FOREIGN KEY (id_work_shedule)
    REFERENCES aptekaru.work_shedules (id_work_shedule) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.supplies
    ADD CONSTRAINT supplies_id_drug_fkey FOREIGN KEY (id_drug)
    REFERENCES aptekaru.drugs (id_drag) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS aptekaru.supplies
    ADD CONSTRAINT supplies_id_pharmacy_fkey FOREIGN KEY (id_pharmacy)
    REFERENCES aptekaru.pharmacies (id_pharmacy) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
