# local      база  пользователь  метод-аутентификации  [параметры-аутентификации]
# host       база  пользователь  адрес  метод-аутентификации  [параметры-аутентификации]
# hostssl    база  пользователь  адрес  метод-аутентификации  [параметры-аутентификации]
# hostnossl  база  пользователь  адрес  метод-аутентификации  [параметры-аутентификации]
# host       база  пользователь  IP-адрес  IP-маска  метод-аутентификации  [параметры-аутентификации]
# hostssl    база  пользователь  IP-адрес  IP-маска  метод-аутентификации  [параметры-аутентификации]
# hostnossl  база  пользователь  IP-адрес  IP-маска  метод-аутентификации  [параметры-аутентификации]

# Внешние подключение
host aptekaru postgres 10.10.0.0/16 scram-sha-256

# Для реплики
host replication replicator 10.10.1.2/32 scram-sha-256

# Для мониторинга
host aptekaru mon_user 10.10.0.0/16 scram-sha-256

# Для отладки localhost
host aptekaru postgres localhost scram-sha-256

# Для unix сокетов
local all postgres scram-sha-256
